### ISSUE TITLE
Running two OpenCTI Instances not Working

### ISSUE THREAD

**Issue by Bauboo** [OpenCTI-Platform/docker#30]
## Description

I cannot run two OpenCTI instances in parallel on the same VM. ElasticSearch is constantly restarting.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.5 LTS
2. OpenCTI version: 4.5.4
3. Other environmental details: nginx

## Setup

1. Create two OpenCTI instances in two separate folders that are identical except for port configuration (80:80 vs 8080:80 in docker-compose config of nginx)
2. Verify that both can run separately and are accessible on their respective port
3. Let both run in parallel

The Docker containers do not have the same names across the two instances. Docker-compose creates two separate docker networks, one per instance. Volumes mapped to the host are mapped to two different locations. Per my understanding, it should be possible to run two OpenCTI instances in parallel with this setup.

## Expected Output

Two OpenCTI instances running in parallel, one on port 80 and one on port 8080.

## Actual Output

It is not working.

In the OpenCTI instance that is started second:  
All connector and the OpenCTI worker docker containers are constantly restarting, as they are waiting for the OpenCTI API to be reachable, which is not reachable because The OpenCTI platform docker container is also constantly restarting. It in turn is waiting for ElasticSearch to be up and also constantly restarting.

In the OpenCTI instance that is started first:  
All containers continue running, except ElasticSearch.

In both instances, the ElasticSearch container is restarting every 30 seconds. Hence I assume that the error has to do with the ElasticSearch containers.

## Additional information

I am not a docker-compose expert, it is entirely possible that I missed something.

Log Elastic Search first instance, after first restart:

```jsonl
{"type": "server", "timestamp": "2021-06-15T12:39:51,614Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "77134d5676d3", "message": "version[7.12.1], pid[8], build[default/docker/3186837139b9c6b6d23c3200870651f10d3343b7/2021-04-20T20:56:39.040728659Z], OS[Linux/5.3.0-62-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/16/16+36]" }
{"type": "server", "timestamp": "2021-06-15T12:39:51,616Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "77134d5676d3", "message": "JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]" }
{"type": "server", "timestamp": "2021-06-15T12:39:51,617Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "77134d5676d3", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-358196448070951726, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms31744m, -Xmx31744m, -XX:MaxDirectMemorySize=16642998272, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=25, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
```

Log Elastic Search second instance (from  a separate try, that is why the time stamps are not similar to the ones above):

```jsonl
{"type": "server", "timestamp": "2021-06-15T12:35:55,967Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ce2909395a10", "message": "version[7.12.1], pid[8], build[default/docker/3186837139b9c6b6d23c3200870651f10d3343b7/2021-04-20T20:56:39.040728659Z], OS[Linux/5.3.0-62-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/16/16+36]" }
{"type": "server", "timestamp": "2021-06-15T12:35:55,970Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ce2909395a10", "message": "JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]" }
{"type": "server", "timestamp": "2021-06-15T12:35:55,970Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ce2909395a10", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-704385226463528375, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms31744m, -Xmx31744m, -XX:MaxDirectMemorySize=16642998272, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=25, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
```

### Configuration Port 80

<details>
<summary>core</summary>
<br>

```yml
version: "3"
services:
  opencti-redis:
    image: redis:6.2.3
    container_name: openCTI-redis
    volumes:
      - /data/master/openCTI/redis:/data
    restart: always

  opencti-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: openCTI-es
    volumes:
      - /data/master/openCTI/es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always

  opencti-minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    container_name: openCTI-minio
    volumes:
      - /data/master/openCTI/minio:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    restart: always

  opencti-rabbitmq:
    image: rabbitmq:3.8-management
    container_name: openCTI-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - /data/master/openCTI/rabbitmq:/var/lib/rabbitmq
    restart: always

  opencti:
    image: opencti/platform:4.5.4
    container_name: openCTI
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=${OPENCTI_PORT}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__LOGS_LEVEL=error
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false

      - REDIS__HOSTNAME=opencti-redis
      - REDIS__PORT=6379

      - ELASTICSEARCH__URL=http://opencti-es:9200

      - MINIO__ENDPOINT=opencti-minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO_SECRET_KEY}

      - RABBITMQ__HOSTNAME=opencti-rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}

      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    depends_on:
      - opencti-redis
      - opencti-es
      - opencti-minio
      - opencti-rabbitmq
    restart: always

  opencti-worker:
    image: opencti/worker:4.5.4
    container_name: openCTI-worker
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 10
    restart: always
```

</details>

<details>
<summary>connectors</summary>
<br>

```yml
version: "3"
services:
# import/export
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:4.5.4
    container_name: connector-export-file-stix
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_LOG_LEVEL=info
    restart: always

  connector-export-file-csv:
    image: opencti/connector-export-file-csv:4.5.4
    container_name: connector-export-file-csv
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_LOG_LEVEL=info
    restart: always

  connector-import-file-stix:
    image: opencti/connector-import-file-stix:4.5.4
    container_name: connector-image-file-stix
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID}
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=false
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_LOG_LEVEL=info
    restart: always

  connector-import-report:
    image: opencti/connector-import-report:4.5.4
    container_name: connector-import-report
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_REPORT_ID}
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportReport
      - CONNCETOR_AUTO=false # Enable/disable auto-import of file
      - CONNCETOR_ONLY_CONTEXTUAL=true # Only extract data related to an entity (a report, a threat actor, etc.)
      - CONNECTOR_SCOPE=application/pdf,text/plain
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_LOG_LEVEL=info
      - IMPORT_REPORT_CREATE_INDICATOR=false
    restart: always

  connector-history:
      image: opencti/connector-history:4.5.4
      container_name: connector-history
      environment:
        - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
        - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
        - CONNECTOR_ID=${CONNECTOR_HISTORY_ID}
        - CONNECTOR_TYPE=STREAM
        - CONNECTOR_NAME=History
        - CONNECTOR_SCOPE=history
        - CONNECTOR_CONFIDENCE_LEVEL=15
        - CONNECTOR_LOG_LEVEL=info
      restart: always

# basic definitions/data
  connector-opencti:
        image: opencti/connector-opencti:4.5.4
        container_name: connector-openCTI
        environment:
          - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
          - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
          - CONNECTOR_ID=${CONNECTOR_OPENCTI_ID}
          - CONNECTOR_TYPE=EXTERNAL_IMPORT
          - CONNECTOR_NAME=OpenCTI
          - CONNECTOR_SCOPE=marking-definition,identity,location
          - CONNECTOR_CONFIDENCE_LEVEL=100
          - CONNECTOR_UPDATE_EXISTING_DATA=true
          - CONNECTOR_LOG_LEVEL=info
          - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
          - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
          - CONFIG_INTERVAL=7
        restart: always
    
  connector-mitre:
    image: opencti/connector-mitre:4.5.4
    container_name: connector-mitre
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE ATT&CK
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,external-reference-as-report
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_MOBILE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json
      - MITRE_INTERVAL=7
    restart: always

  connector-cve:
      image: opencti/connector-cve:4.5.4
      container_name: connector-cve
      environment:
        - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
        - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
        - CONNECTOR_ID=${CONNECTOR_CVE_ID}
        - CONNECTOR_TYPE=EXTERNAL_IMPORT
        - CONNECTOR_NAME=Common Vulnerabilities and Exposures
        - CONNECTOR_SCOPE=identity,vulnerability
        - CONNECTOR_CONFIDENCE_LEVEL=75
        - CONNECTOR_UPDATE_EXISTING_DATA=true
        - CONNECTOR_LOG_LEVEL=info
        - CVE_IMPORT_HISTORY=true
        - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
        - CVE_HISTORY_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/
        - CVE_INTERVAL=2 # in days, must be strictly greater than 1
      restart: always
```

</details>

<details>
<summary>nginx</summary>
<br>

```yml
version: "3"
services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - opencti
    restart: always
```

</details>

### Configuration Port 8080

This config is basically the same as for the port 80 instance.

<details>
<summary>core</summary>
<br>

```yml
version: "3"
services:
  opencti-redis:
    image: redis:6.2.3
    container_name: openCTI-redis-dev
    volumes:
      - /data/master/openCTI-dev/redis:/data
    restart: always

  opencti-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: openCTI-es-dev
    volumes:
      - /data/master/openCTI-dev/es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always

  opencti-minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    container_name: openCTI-minio-dev
    volumes:
      - /data/master/openCTI-dev/minio:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    restart: always

  opencti-rabbitmq:
    image: rabbitmq:3.8-management
    container_name: openCTI-rabbitmq-dev
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - /data/master/openCTI-dev/rabbitmq:/var/lib/rabbitmq
    restart: always

  opencti:
    image: opencti/platform:4.5.4
    container_name: openCTI-dev
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=${OPENCTI_PORT}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__LOGS_LEVEL=error
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false

      - REDIS__HOSTNAME=opencti-redis
      - REDIS__PORT=6379

      - ELASTICSEARCH__URL=http://opencti-es:9200

      - MINIO__ENDPOINT=opencti-minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO_SECRET_KEY}

      - RABBITMQ__HOSTNAME=opencti-rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}

      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    depends_on:
      - opencti-redis
      - opencti-es
      - opencti-minio
      - opencti-rabbitmq
    restart: always

  opencti-worker:
    image: opencti/worker:4.5.4
    container_name: openCTI-worker-dev
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 10
    restart: always
```

</details>

<details>
<summary>connectors</summary>
<br>

```yml
version: "3"
services:
# import/export
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:4.5.4
    container_name: connector-export-file-stix-dev
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_LOG_LEVEL=info
    restart: always

  connector-export-file-csv:
    image: opencti/connector-export-file-csv:4.5.4
    container_name: connector-export-file-csv-dev
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_LOG_LEVEL=info
    restart: always

  connector-import-file-stix:
    image: opencti/connector-import-file-stix:4.5.4
    container_name: connector-image-file-stix-dev
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID}
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=false
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_LOG_LEVEL=info
    restart: always

  connector-import-report:
    image: opencti/connector-import-report:4.5.4
    container_name: connector-import-report-dev
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_REPORT_ID}
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportReport
      - CONNCETOR_AUTO=false # Enable/disable auto-import of file
      - CONNCETOR_ONLY_CONTEXTUAL=true # Only extract data related to an entity (a report, a threat actor, etc.)
      - CONNECTOR_SCOPE=application/pdf,text/plain
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_LOG_LEVEL=info
      - IMPORT_REPORT_CREATE_INDICATOR=false
    restart: always

  connector-history:
      image: opencti/connector-history:4.5.4
      container_name: connector-history-dev
      environment:
        - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
        - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
        - CONNECTOR_ID=${CONNECTOR_HISTORY_ID}
        - CONNECTOR_TYPE=STREAM
        - CONNECTOR_NAME=History
        - CONNECTOR_SCOPE=history
        - CONNECTOR_CONFIDENCE_LEVEL=15
        - CONNECTOR_LOG_LEVEL=info
      restart: always

# basic definitions/data
  connector-opencti:
        image: opencti/connector-opencti:4.5.4
        container_name: connector-openCTI-dev
        environment:
          - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
          - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
          - CONNECTOR_ID=${CONNECTOR_OPENCTI_ID}
          - CONNECTOR_TYPE=EXTERNAL_IMPORT
          - CONNECTOR_NAME=OpenCTI
          - CONNECTOR_SCOPE=marking-definition,identity,location
          - CONNECTOR_CONFIDENCE_LEVEL=100
          - CONNECTOR_UPDATE_EXISTING_DATA=true
          - CONNECTOR_LOG_LEVEL=info
          - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
          - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
          - CONFIG_INTERVAL=7
        restart: always
    
  connector-mitre:
    image: opencti/connector-mitre:4.5.4
    container_name: connector-mitre-dev
    environment:
      - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE ATT&CK
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set,campaign,malware,tool,report,external-reference-as-report
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_MOBILE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json
      - MITRE_INTERVAL=7
    restart: always

  connector-cve:
      image: opencti/connector-cve:4.5.4
      container_name: connector-cve-dev
      environment:
        - OPENCTI_URL=http://opencti:${OPENCTI_PORT}
        - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
        - CONNECTOR_ID=${CONNECTOR_CVE_ID}
        - CONNECTOR_TYPE=EXTERNAL_IMPORT
        - CONNECTOR_NAME=Common Vulnerabilities and Exposures
        - CONNECTOR_SCOPE=identity,vulnerability
        - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
        - CONNECTOR_UPDATE_EXISTING_DATA=true
        - CONNECTOR_LOG_LEVEL=info
        - CVE_IMPORT_HISTORY=true # Import history at the first run (after only recent), reset the connector state if you want to re-import
        - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
        - CVE_HISTORY_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/
        - CVE_INTERVAL=2 # In days, must be strictly greater than 1
      restart: always
```

</details>

<details>
<summary>nginx</summary>
<br>

```yml
version: "3"
services:
  web:
    image: nginx
    container_name: nginx-dev
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - opencti
    restart: always
```

</details>
