### ISSUE TITLE
Support the use of environment file .env  

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/docker#5]
Compose supports declaring default environment variables in an environment file named `.env` placed in the folder where the docker-compose command is executed (current working directory). [Source](https://docs.docker.com/compose/env-file/) 

So, instead of editing `docker-compose.yml`, we could just execute:

```bash
echo "APP__ADMIN__TOKEN=$(cat /proc/sys/kernel/random/uuid)" > .env
echo "APP__ADMIN__PASSWORD=MySecret" >> .env
..
docker-compose --compatibility up
```
No need to edit the original `docker-compose.yml` and no more risk of uploading it to github :)

Another option is to use `docker-compose.override.yml`, see https://docs.docker.com/compose/extends/#multiple-compose-files

**Comment by GlennHD** [comment]
I like the solution mentioned by @2xyo. Personally, I just made a `.env` file and replaced all the values with variables in the `docker-compose.yml` file.  I'm sure there are better ways to do this but I'm just tinkering for now and found this solution to help me keep things simple.
### My `.env` file located at `/opt/opencti/docker/.env`
```
OPEN_CTI_USERNAME=email@address
OPEN_CTI_PASSWORD=Password1234
RABBITMQ_USERNAME=rabbitmq
RABBITMQ_PASSWORD=Password1234
MINIO_USERNAME=minio
MINIO_PASSWORD=Password1234
OPEN_CTI_TOKEN=XXXXXXXXXXXXX
CONNECTOR_EXPORT_FILE_STIX_TOKEN=XXXXXXXXXXXXX
CONNECTOR_IMPORT_FILE_STIX_TOKEN=XXXXXXXXXXXXX
CONNECTOR_OPENCTI_TOKEN=XXXXXXXXXXXXX
CONNECTOR_MITRE_TOKEN=XXXXXXXXXXXXX
CONNECTOR_IPINFO_TOKEN=XXXXXXXXXXXXX
CONNECTOR_CVE_TOKEN=XXXXXXXXXXXXX
IPINFO_TOKEN=XXXXXXXXXXXXX
```

### My `docker-compose.yml` file located at `/opt/opencti/docker/docker-compose.yml`
```
version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.9
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_USERNAME}
      MINIO_SECRET_KEY: ${MINIO_PASSWORD}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.7.17-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}    
    restart: always
  opencti:
    image: opencti/platform:latest
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=${OPEN_CTI_USERNAME}
      - APP__ADMIN__PASSWORD=${OPEN_CTI_PASSWORD}
      - APP__ADMIN__TOKEN=${OPEN_CTI_TOKEN}
      - APP__LOGS_LEVEL=error
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_USERNAME}
      - MINIO__SECRET_KEY=${MINIO_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ__PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPEN_CTI_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 10
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPEN_CTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_TOKEN}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPEN_CTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_TOKEN}
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
  connector-opencti:
    image: opencti/connector-opencti:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPEN_CTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_OPENCTI_TOKEN}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=OpenCTI
      - CONNECTOR_SCOPE=identity,sector,region,country,city
      - CONNECTOR_CONFIDENCE_LEVEL=5
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_INTERVAL=7 # Days
    depends_on:
      - opencti
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPEN_CTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_TOKEN}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE ATT&CK
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_INTERVAL=7 # Days
    restart: always
  connector-ipinfo:
    image: opencti/connector-ipinfo:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPEN_CTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IPINFO_TOKEN}
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=IpInfo
      - CONNECTOR_SCOPE='ipv4-addr'
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - IPINFO_TOKEN=${IPINFO_TOKEN}
    restart: always  
  connector-cve:
    image: opencti/connector-cve:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPEN_CTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_CVE_TOKEN}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Common Vulnerabilities and Exposures
      - CONNECTOR_SCOPE=identity,vulnerability
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.json.gz
      - CVE_INTERVAL=3 # Days
    restart: always
volumes:
  grakndata:
  esdata:
  s3data:
```
