### ISSUE TITLE
Problem with connectors (Error 500 : ConnectorsStatusQuery)

### ISSUE THREAD

**Issue by DeltaPh0** [OpenCTI-Platform/docker#57]
**Description :**
I installed OpenCTI 5.2.4 with Docker. I encounter a problem when I go to the Data > Connectors tab, where it says "_An unknown error occurred. Please contact your administrator or the OpenCTI maintainers_".
I guess the error is coming from RabbitMQ, but I don't know how to solve this problem.

![image](https://user-images.githubusercontent.com/103181325/167845856-58d6c05a-8b95-4bbe-9c62-0e22489512d4.png)

**Environment :**

- Docker version : 20.10.15
- OpenCTI version : 5.2.4
- RabbitMQ 3.9.17
- Erlang 24.3.4

**Docker-compose file :**
```yaml
version: '3'
services:
  redis:
    image: redis:6.2.6
    restart: unless-stopped
    volumes:
      - redisdata:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2022-02-26T02-54-46Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
  opencti:
    image: opencti/platform:5.2.4
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=5678
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=info
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "5678:5678"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: unless-stopped
  connector-history:
    image: opencti/connector-history:5.2.4
    environment:
      - OPENCTI_URL=http://opencti:5678
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_HISTORY_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=STREAM
      - CONNECTOR_NAME=History
      - CONNECTOR_SCOPE=history
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      - opencti
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:5.2.4
    environment:
      - OPENCTI_URL=http://opencti:5678
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      - opencti
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:5.2.4
    environment:
      - OPENCTI_URL=http://opencti:5678
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      - opencti
  connector-export-file-txt:
    image: opencti/connector-export-file-txt:5.2.4
    environment:
      - OPENCTI_URL=http://opencti:5678
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_TXT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileTxt
      - CONNECTOR_SCOPE=text/plain
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      - opencti
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:5.2.4
    environment:
      - OPENCTI_URL=http://opencti:5678
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      - opencti
  connector-import-document:
    image: opencti/connector-import-document:5.2.4
    environment:
      - OPENCTI_URL=http://opencti:5678
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportDocument
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/pdf,text/plain,text/html
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_ONLY_CONTEXTUAL=false # Only extract data related to an entity (a report, a threat actor, etc.)
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - IMPORT_DOCUMENT_CREATE_INDICATOR=true
    restart: unless-stopped
    depends_on:
      - opencti

volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:
```

**OpenCTI Logs :**

```text
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-05-11T11:41:28.642Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[SEARCH ENGINE] Elasticsearch (7.17.1) client selected / runtime sorting enabled","timestamp":"2022-05-11T11:41:28.731Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2022-05-11T11:41:28.731Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2022-05-11T11:41:28.748Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2022-05-11T11:41:28.769Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2022-05-11T11:41:28.778Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2022-05-11T11:41:28.780Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2022-05-11T11:41:29.124Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2022-05-11T11:41:29.127Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2022-05-11T11:41:29.129Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2022-05-11T11:41:29.270Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[INIT] admin user initialized","timestamp":"2022-05-11T11:41:29.581Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[MIGRATION] Read 0 migrations from the database","timestamp":"2022-05-11T11:41:29.643Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[MIGRATION] Platform already up to date, nothing to migrate","timestamp":"2022-05-11T11:41:29.643Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[MIGRATION] Migration process completed","timestamp":"2022-05-11T11:41:29.644Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[MIGRATION] Platform version updated to 5.2.4","timestamp":"2022-05-11T11:41:29.686Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2022-05-11T11:41:29.686Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[OPENCTI] API ready on port 5678","timestamp":"2022-05-11T11:41:30.397Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running Expiration manager","timestamp":"2022-05-11T11:41:30.397Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running retention manager","timestamp":"2022-05-11T11:41:30.397Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running task manager","timestamp":"2022-05-11T11:41:30.398Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Subscription manager not started (disabled by configuration)","timestamp":"2022-05-11T11:41:30.418Z","version":"5.2.4"}
{"auth":{"email":"admin@opencti.io","ip":"172.18.0.2","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2022-05-11T11:41:30.688Z","version":"5.2.4"}
{"auth":{"email":"admin@opencti.io","ip":"172.18.0.8","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2022-05-11T11:41:32.148Z","version":"5.2.4"}
{"auth":{"email":"admin@opencti.io","ip":"172.18.0.11","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2022-05-11T11:41:32.491Z","version":"5.2.4"}
{"auth":{"email":"admin@opencti.io","ip":"172.18.0.12","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2022-05-11T11:41:33.465Z","version":"5.2.4"}
{"auth":{"email":"admin@opencti.io","ip":"172.18.0.12","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2022-05-11T11:41:33.703Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[STREAM] Starting stream processor for admin@opencti.io","timestamp":"2022-05-11T11:41:33.707Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'admin@opencti.io' client ready","timestamp":"2022-05-11T11:41:33.709Z","version":"5.2.4"}
{"auth":{"email":"admin@opencti.io","ip":"172.18.0.6","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2022-05-11T11:41:34.574Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Running rule manager","timestamp":"2022-05-11T11:41:40.419Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[STREAM] Starting stream processor for Rule manager","timestamp":"2022-05-11T11:41:40.430Z","version":"5.2.4"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Rule manager' client ready","timestamp":"2022-05-11T11:41:40.432Z","version":"5.2.4"}
{"auth":{"email":"admin@opencti.io","ip":"172.18.0.7","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","level":"info","message":"LOGIN","resource":{"provider":"Bearer"},"timestamp":"2022-05-11T11:41:40.632Z","version":"5.2.4"}
{"category":"APP","error":{"stacktrace":["Error: Request failed with status code 500","at createError (/opt/opencti/build/node_modules/axios/lib/core/createError.js:16:15)","at settle (/opt/opencti/build/node_modules/axios/lib/core/settle.js:17:12)","at IncomingMessage.handleStreamEnd (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:312:11)","at IncomingMessage.emit (node:events:406:35)","at endReadableNT (node:internal/streams/readable:1331:12)","at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"ConnectorsStatusQuery","operation_query":"query ConnectorsStatusQuery{...ConnectorsStatus_data}fragment ConnectorsStatus_data on Query{connectors{id name active auto connector_type connector_scope updated_at config{listen listen_exchange push push_exchange}}rabbitMQMetrics{queues{name messages messages_ready messages_unacknowledged consumers idle_since message_stats{ack ack_details{rate}}}}}","size":2,"time":15,"timestamp":"2022-05-11T11:43:11.660Z","type":"READ_ERROR","user":{"ip":"172.18.0.1","referer":"http://localhost:5678/dashboard/data/connectors","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{},"version":"5.2.4"}
{"category":"APP","error":{"stacktrace":["Error: Request failed with status code 500","at createError (/opt/opencti/build/node_modules/axios/lib/core/createError.js:16:15)","at settle (/opt/opencti/build/node_modules/axios/lib/core/settle.js:17:12)","at IncomingMessage.handleStreamEnd (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:312:11)","at IncomingMessage.emit (node:events:406:35)","at endReadableNT (node:internal/streams/readable:1331:12)","at processTicksAndRejections (node:internal/process/task_queues:83:21)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"WorkersStatusQuery","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","size":2,"time":25,"timestamp":"2022-05-11T11:43:11.665Z","type":"READ_ERROR","user":{"ip":"172.18.0.1","referer":"http://localhost:5678/dashboard/data/connectors","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{},"version":"5.2.4"}
```

**Status of RabbitMQ :**
![image](https://user-images.githubusercontent.com/103181325/167847852-30c506f7-9fa5-4295-9a54-eef294be5c66.png)
So the connectors containers seem to be well connected to RabbitMQ, only the Data > Connectors query from OpenCTI generates an error.

Any help would be much appreciated.
